# Generated by Django 4.2.5 on 2023-11-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=50)),
                ('emobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('eaddress', models.CharField(max_length=200)),
                ('edate', models.DateField()),
            ],
        ),
    ]
